version: "3.8"

services:
    # Frontend service
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: qrcode-frontend
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - backend
        networks:
            - qrcode-network

    # Backend service
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: qrcode-backend
        restart: unless-stopped
        ports:
            - "8000:8000"
        environment:
            - DEBUG=False
            - SECRET_KEY=your-secret-key-change-this-in-production
            - ALLOWED_HOSTS=localhost,127.0.0.1,frontend
            - DOMAIN=72.155.88. # Change this to your actual domain
        volumes:
            - backend_data:/app/media
            - backend_static:/app/static
        networks:
            - qrcode-network

volumes:
    backend_data:
        driver: local
    backend_static:
        driver: local

networks:
    qrcode-network:
        driver: bridge
