services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
            - media:/app/media
        environment:
            - DEBUG=1

    frontend:
        build: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend

volumes:
    media:
