# Generated by Django 5.2.4 on 2025-08-06 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('image', models.ImageField(upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'qrcode_qrcode',
            },
        ),
        migrations.CreateModel(
            name='QRBatch',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qrcodes', models.ManyToManyField(related_name='batches', to='qrcode_generator.qrcode')),
            ],
            options={
                'db_table': 'qrcode_qrbatch',
            },
        ),
    ]
